---
tags: Rhino-Python-Primer-101
icon: material/ladybug
# categories: book
# authors:
#     - Alex
# date: 
#     created: 2022-01-20 21:30:07
#     updated: 2024-07-03 20:11:43
# icon: material/book
status: new
---
# :material-book:{.red} Rev3ç¨‹åºå‹˜è¯¯
Rhino Python Primer 101è¿™æœ¬ä¹¦æ˜¯å®˜æ–¹å‡ºç‰ˆçš„å­¦ä¹ pythonç¼–ç¨‹åœ¨Rhinoä¸­åº”ç”¨çš„æ‰‹å†Œã€‚

æ²¡æœ‰ä¸­æ–‡ç‰ˆï¼Œè¿™ä¸æ˜¯é—®é¢˜ï¼Œå’±å­¦è‹±æ–‡ï¼›ä½†æ˜¯æœ‰ä¸€ç‚¹æ¯”è¾ƒå‘çš„æ˜¯ï¼Œé‡Œé¢çš„ç¨‹åºæ²¡æœ‰ç»è¿‡ä»”ç»†çš„æ ¡å¯¹ï¼Œæ€è·¯éƒ½æ˜¯å¯¹çš„ï¼Œä½†æ˜¯åªè¦ä¸€ä¸Šæ‰‹è¿è¡Œå°±ä¼šå‘ç°å„ç§é”™è¯¯ã€‚
å› ä¸ºç¨‹åºæ˜¯å¾ˆä¸¥è°¨çš„ï¼Œå°±åƒä¹¦é‡Œè‡ªå·±ä¹Ÿè¯´äº†pythonå¤§å°å†™æ•æ„Ÿï¼Œåªè¦é”™äº†ä¸€ä¸ªå­—æ¯ï¼Œå°±æ˜¯è¿è¡Œä¸èµ·æ¥ã€‚è¿™å¯ææ€–äº†ï¼ŒåŠ äº†ä¸¤å±‚buffï¼Œä¸€æ˜¯è‹±æ–‡é¦–å…ˆå°±ä¸å¥½ç†è§£äº†ï¼Œå†åŠ ä¸Šç¨‹åºé”™è¯¯ï¼Œæå®¹æ˜“äº§ç”Ÿçš„æƒ…ç»ªæ˜¯å­¦ä¹ ä¸€ä¸‹å°±å‘ç°è¿›è¡Œä¸ä¸‹å»äº†ï¼Œå¾ˆæ²®ä¸§ã€‚

!!! info "ğŸ¤³è¯·çœ‹ä½œè€…ç«‹çš„FLAG"
    
    All the example code in this primer can be copy-pasted directly into the _EditPythonScript dialog.<BR>
    æœ¬å…¥é—¨æ‰€æœ‰ä»£ç å¯ç›´æ¥å¤åˆ¶ç²˜è´´è‡³ *_EditPythonScript* å¯¹è¯æ¡†ã€‚


ä½†æ˜¯æˆ‘ä¸æ€•å›°éš¾ï¼Œä¸€å­¦è‹±è¯­ï¼ŒäºŒå­¦ç¼–ç¨‹ã€‚ä¸¤æ‰‹éƒ½è¦æŠ“ï¼Œä¸¤æ‰‹éƒ½è¦ç¡¬ã€‚å¯¹å­¦ä¹ è¿‡çš„ç¨‹åºï¼Œéƒ½éœ€è¦è¿è¡Œä¸€éï¼Œä»¥åœ¨ç”µè„‘ä¸Šè¿è¡Œé€šè¿‡ä¸ºæ ‡å‡†ï¼Œå¯¹ä¹¦ä¸­çš„ç¨‹åºè¿›è¡Œä¸€æ¬¡å¤§æ‰«é™¤ã€‚
é¦–å…ˆè¿è¡Œç¯å¢ƒæ˜¯ï¼š
```python
import sys
print(sys.version)
```
!!! note ""
    
    `2.7.9 (IronPython 2.7.9 (2.7.9.0) on .NET 4.0.30319.42000 (64-bit))`<br>
    **Rhino 7.12**


ä»¥ä¸‹æ˜¯æ‰«é™¤è¿‡ç¨‹ã€‚
<!--MORE-->
## ç¬¬1ç«  è¿™æ˜¯å•¥ç©æ„å„¿
å…´å†²å†²çš„å­¦ä¹ èµ·æ¥ï¼Œæœ¬ä¹¦çš„ç¬¬ä¸€ä¸ªç¤ºä¾‹ç¨‹åºå°±ç»™ä½ ä¸€ä¸ªä¸‹é©¬å¨ã€‚ä½ è¦æ˜¯æŠŠä¸‹é¢è¿™åŸä¹¦ä»£ç ç›´æ¥å¤åˆ¶å¹¶ç»‘å®šåˆ°ä¸€ä¸ªæŒ‰é’®ä¸Š(é»˜è®¤ä½ å·²ç»ä¼šè¿™æ ·åšäº†)ã€‚ä¿è¯ä½ è¿è¡Œä¸äº†ï¼š
```java
_SelNone
_Polygon _NumSides=6 w0,0,0 w10,0,0
_SelLast
-_Properties _Object _Name RailPolygon _Enter _Enter
_SelNone
_Polygon _NumSides=6 w10,0,0 w12,0,0
_SelLast
_Rotate3D w0,0,0 w10,0,0 90
-_Properties _Object _Name ProfilePolygon _Enter _Enter
_SelNone
-_Sweep1 _SelName RailPolygon _SelName ProfilePolygon _Enter _Enter _Closed=Yes Enter
```
ç›´æ¥è¿è¡Œä¼šå¼¹å‡ºä¸ªçª—å£ï¼Œç„¶åè¦ä½ é€‰æ‹©ï¼Œæ— è®ºä½ æ€ä¹ˆé€‰æœ€åéƒ½ç”Ÿæˆä¸äº†ä¹¦ä¸Šè¿™ç©æ„ã€‚å¯¹æ–°æ‰‹æä¸å‹å¥½ï¼Œå¾ˆå¤šäººå°±æ”¾å¼ƒäº†ã€‚ä¹¦çš„ä½œè€…å¯èƒ½ï¼Œå°±å®Œå…¨æ²¡è¿è¡Œè¿‡è‡ªå·±å†™çš„è¿™æ®µå®ï¼Œè¿˜ä¸å¦‚ä¸è´´å‘¢ï¼Œæ‰“å‡»äº†å¤šå°‘äººçš„ç§¯ææ€§ã€‚

<figure markdown>
  ![Hexagonaltorus](https://cdn.jsdelivr.net/gh/chinabiue/img@latest/rhino101/hexagonaltorus.svg){ width="400" }
  <figcaption>Polygon</figcaption>
</figure>

é—®é¢˜åœ¨å“ªå‘¢ï¼Ÿæˆ‘æ¥ç»™å‡ºç­”æ¡ˆï¼šé—®é¢˜åœ¨æœ€åä¸€è¡Œå‘½ä»¤æœ‰å·¨å¤§é—®é¢˜ã€‚

`-_Sweep1 _SelName RailPolygon _SelName ProfilePolygon _Enter _Enter _Closed=Yes Enter`

ä¸»è¦2ä¸ªé—®é¢˜ï¼š

1. ä½œè€…è‡ªå·±ä¹Ÿè¯´äº†ï¼Œ'-'è¿™ä¸ªç¬¦å·æ˜¯è®©å‘½ä»¤è¿è¡Œä¸å¼¹å‡ºçª—å£ä¸ç”¨æˆ·äº¤äº’ï¼Œå¯æ˜¯ä»–è‡ªå·±é©¬ä¸Šå°±é£Ÿè¨€äº†ï¼Œç”©å‡ºä¸¤ä¸ª`_SelName`è®©çª—å£å¼¹å‡ºï¼Œæ–°æ‰‹æªæ‰‹ä¸åŠï¼Œä¸çŸ¥é“å‘ç”Ÿäº†ä»€ä¹ˆã€‚æ— è®ºå’‹ç‚¹ä¹Ÿä¸æˆåŠŸã€‚
   
2. `_Closed=Yes Enter`è¿™åœ¨ä¸­æ–‡ç•Œé¢ä¸‹è¡Œä¸é€šï¼ŒClosed=Yesè®¾ç½®å‚æ•°ï¼Œå¹¶ä¸æ˜¯å‘½ä»¤ï¼Œå‰é¢å¹¶ä¸éœ€è¦åŠ ä¸‹åˆ’çº¿`_`ï¼›éœ€è¦åŠ ä¸‹åˆ’çº¿`_`çš„Enteråˆä¸åŠ ã€‚åè¡€ã€‚

3. åœ¨ç¨‹åºç•Œé¢è¯­è¨€ä¸ºä¸­æ–‡çš„æƒ…å†µä¸‹ï¼Œåªèƒ½ä½¿ç”¨å‘½ä»¤ç®€å†™è®©ç¨‹åºå®Œå…¨æ— è¯¯çš„è¿è¡Œï¼Œæ„æ€å°±æ˜¯`_C`
   
4. è¯·åœ¨Top/Perspective/Frontçª—å£ä¸‹è¿è¡Œç¨‹åºï¼Œåœ¨Rightçª—å£è¿è¡Œç¨‹åºä¸ä¼šèµ·ä½œç”¨ã€‚

ä»¥ä¸‹æ˜¯æ”¹æ­£è¿‡çš„ç¨‹åºï¼Œä¸€é”®è¿è¡Œç¨³å¦‚ç‹—ã€‚
(è¿™ä¸ªåšä¸ºè¯•éªŒï¼Œæˆ‘åˆ†æ”¯äº†MCNEELçš„githubåº“ï¼Œæ”¹æ­£äº†è¿™ä¸ªé—®é¢˜ï¼Œå¹¶ä¸”æ¨é€å›MCNEEL,ä»–ä»¬æ¥å—äº†è¿™ä¸ªpull requestå¹¶åˆå¹¶åˆ°ä»–ä»¬çš„ä»“åº“äº†ã€‚ç°åœ¨Rhinoç½‘ä¸Šçš„æ•™ç¨‹éƒ¨åˆ†æ˜¯æ²¡æœ‰é—®é¢˜çš„äº†ï¼Œå’Œæ”¹æ­£è¿‡çš„ä¸€æ ·ã€‚å°±æ˜¯ä¸çŸ¥é“PDFä»–ä»¬æœ‰æ²¡æœ‰é‡æ–°ç”Ÿæˆã€‚)
ç¬¬2é¡µ
```JAVA
_SelNone
_Polygon _NumSides=6 w0,0,0 w10,0,0
_SelLast
-_Properties _Object _Name RailPolygon _Enter _Enter
_SelNone
_Polygon _NumSides=6 w10,0,0 w12,0,0
_SelLast
_Rotate3D w0,0,0 w10,0,0 90
-_Properties _Object _Name ProfilePolygon _Enter _Enter
_SelNone
-_Sweep1 -_SelName RailPolygon -_SelName ProfilePolygon _Enter _Enter _C _Enter
```
## ç¬¬2ç«  PythonåŸºç¡€
ç”¨pythonçš„æ–¹å¼ï¼Œé‡å¤äº†ç¬¬1ç« çš„é”™è¯¯ï¼Œä¸åšåˆ†æäº†ï¼Œç›´æ¥ä¸Šæ”¹è¿›è¿‡åèƒ½è¿è¡Œçš„ä»£ç ã€‚
ç¬¬10é¡µ
```python
import rhinoscriptsyntax as rs

dblMajorRadius = rs.GetReal("Major radius", 10.0, 1.0, 1000.0)
dblMinorRadius = rs.GetReal("Minor radius", 2.0, 0.1, 100.0)
intSides = rs.GetInteger("Number of sides", 6, 3, 20)

strPoint1 = " w" + str(dblMajorRadius) + ",0,0"
strPoint2 = " w" + str(dblMajorRadius + dblMinorRadius) + ",0,0"

rs.Command ("_SelNone")
rs.Command ("_Polygon _NumSides=" + str(intSides) + " w0,0,0" + strPoint1)
rs.Command ("_SelLast")
rs.Command ("-_Properties _Object _Name Rail _Enter _Enter")
rs.Command ("_SelNone")
rs.Command ("_Polygon _NumSides=" + str(intSides) + strPoint1 + strPoint2)
rs.Command ("_SelLast")
rs.Command ("_Rotate3D w0,0,0 w1,0,0 90")
rs.Command ("-_Properties _Object _Name Profile _Enter _Enter")
rs.Command ("_SelNone")
rs.Command ("-_Sweep1 -_SelName Rail -_SelName Profile _Enter _Enter _C _Enter")
rs.Command ("-_SelName Rail")
rs.Command ("-_SelName Profile")
rs.Command ("_Delete")
```

## ç¬¬3ç«  è„šæœ¬ç»“æ„
æ— 

## ç¬¬4ç«  æ“ä½œç¬¦ä¸å‡½æ•°
æ— 

## ç¬¬5ç«  æ¡ä»¶æ‰§è¡Œ
ä»¥ä¸‹ç¨‹åºæ— é”™è¯¯ï¼Œä½†æ˜¯æœ‰å‰¯ä½œç”¨ã€‚è¿è¡Œäº†æ— æ³•åœæ­¢ï¼Œå“ˆå“ˆã€‚è¯·æŠŠç¨‹åºå…³äº†é‡æ–°æ‰“å¼€ã€‚

ç¬¬27é¡µ
```python
import rhinoscriptsyntax as rs
import datetime as dt

def viewportclock():
    now = dt.datetime.now()
    textobject_id = rs.AddText(str(now), (0,0,0), 20)
    if textobject_id is None: return
    rs.ZoomExtents(None, True)
    while True:
        rs.Sleep(1000)
        now = dt.datetime.now()
        rs.TextObjectText(textobject_id, str(now))

if __name__=="__main__":
    viewportclock()
```

## ç¬¬6ç«  å…ƒç»„ã€åˆ—è¡¨å’Œå­—å…¸
åˆä¸€ç¥ä½œï¼Œä¸€æ—¶åŠä¼šååº”ä¸è¿‡æ¥ä¼šé™·å…¥æ— é™å¾ªç¯ã€‚æˆ‘è¢«Rhinoé—®åˆ°æˆ‘ç¬¬242æœ€å–œæ¬¢çš„äº‹æƒ…æ˜¯ä»€ä¹ˆçš„æ—¶å€™ï¼Œå…³é—­äº†ç¨‹åºã€‚

è¿™ç©æ„æœ‰é€€å‡ºæ¡ä»¶ï¼Œä½†æ˜¯å¾ˆéšè”½`if answer is None: break`,å¦‚ä½•åœ¨Rhinoè¾“å…¥ä¸€ä¸ªNoneå€¼å‘¢ï¼Ÿ

1. ç›´æ¥å›è½¦
   
2. æŒ‰ç©ºæ ¼
   
3. æŒ‰é€€æ ¼
   
éƒ½ä¸å¯¹ï¼Œè¯·æŒ‰å·¦ä¸Šè§’`ESC`é”®ï¼Œæˆ‘å¤§æ„äº†ï¼Œæ²¡æœ‰é—ªã€‚

ç¬¬34é¡µ
```python
import rhinoscriptsyntax as rs

def myfavoritethings():
    things = []

    while True:
        count = len(things)
        prompt = "What is your {0}th most favorite thing?".format(count+1)
        if len(things)==0:
            prompt = "What is your most favorite thing?"
        elif count==1:
            prompt = "What is your second most favorite thing?"
        elif count==2:
            prompt = "What is your third most favourite thing?"

        answer = rs.GetString(prompt)
        if answer is None: break
        things.append(answer)
    if len(things)==0: return

    print "Your", len(things)+1, "favorite things are:"
    for i,thing in enumerate(things): print i+1, ".", thing
```

ç¬¬35é¡µï¼Œå·¦è¾¹çš„ç¨‹åºå¹¶ä¸ä¼šäº§ç”Ÿå³å›¾çš„ç»“æœã€‚ä¸‹é¢è¿™ä¸ªç¨‹åºèƒ½ç”Ÿæˆæ¯”è¾ƒåƒå³è¾¹å›¾ã€‚

<figure markdown>
  ![sin_cos](https://cdn.jsdelivr.net/gh/chinabiue/img@latest/basic/sin_cos.png){ width="400" }
  <figcaption>sin_cos</figcaption>
</figure>

```python
import rhinoscriptsyntax as rs
import math

r = -1800
step = 5
for t in rs.frange(0,2*abs(r),step):
    x = r * math.cos(t/360*2*math.pi)
    y = r * math.sin(t/360*2*math.pi)
    z = r
    rs.AddPoint(x,y,z)
    r += step
```

#### åµŒå¥—åˆ—è¡¨
è¿™ä¸€èŠ‚çš„ç¨‹åºï¼Œå¹³æ»‘æ›²çº¿ã€‚é”™è¯¯ä¸€èˆ¬èˆ¬ï¼Œä¸»è¦å°±æ˜¯ç”Ÿæˆæ›²çº¿èŠ‚ç‚¹æ•°ä¸é˜¶æ•°æœ‰ä¸€ä¸ªå…³ç³»ï¼š

$$K_N = P_N + (D-1)$$

smoothcurve()è¿™ä¸ªå‡½æ•°æ¼æ‰äº†èµ·ç‚¹å’Œç»ˆç‚¹ï¼Œå¯¼è‡´ä¸ç¬¦åˆå…¬å¼ä»¥è‡´äºæ— æ³•ç”»å‡ºæœ€åå¹³æ»‘çš„æ›²çº¿ã€‚

```python
import rhinoscriptsyntax as rs

def smoothingvector(point, prev_point, next_point, s):
    pm = (prev_point+next_point)/2.0
    va = rs.VectorCreate(pm, point)
    vm = rs.VectorScale(va, s)
    return vm

def smoothcurve(curve_id, s):
    curve_points = rs.CurvePoints(curve_id)
    new_curve_points = []
    new_curve_points.append(curve_points[0])    # miss 1st point
    for i in range(1, len(curve_points)-1):
        vm = smoothingvector(curve_points[i], curve_points[i-1], curve_points[i+1], s)
        new_curve_points.append( rs.PointAdd(curve_points[i], vm) )
    new_curve_points.append(curve_points[-1])    # miss last point

    knots = rs.CurveKnots(curve_id)
    degree = rs.CurveDegree(curve_id)
    weights = rs.CurveWeights(curve_id,0)
    newcurve_id = rs.AddNurbsCurve(new_curve_points, knots, degree, weights)
    if newcurve_id: rs.DeleteObject(curve_id)
    return newcurve_id


def iterativeshortencurve():
    curve_id = rs.GetObject("Open curve to smooth", 4, True)
    if curve_id is None or rs.IsCurveClosed(curve_id): return

    min = rs.Distance(rs.CurveStartPoint(curve_id), rs.CurveEndPoint(curve_id))
    max = rs.CurveLength(curve_id)
    goal = rs.GetReal("Goal length", 0.5*(min+max) , min, max)
    if goal is None: return

    while rs.CurveLength(curve_id)>goal:
        rs.EnableRedraw(False)
        curve_id = smoothcurve(curve_id, 0.1)
        rs.EnableRedraw(True)
        if curve_id is None: break

iterativeshortencurve()
```
## ç¬¬7ç«  ç±»
æ— 

## ç¬¬8ç«  å‡ ä½•ä½“
æ ¸å¿ƒç¯‡ç« ï¼Œé‡ç¾åŒºï¼Œè¶Šæ˜¯é‡è¦çš„åœ°æ–¹å‡ºé”™è¶Šå¤šã€‚å› ä¸ºç¨‹åºå¤æ‚æ€§ä¸Šå‡äº†ä¸€ä¸ªç¨‹åº¦ã€‚
### 8.4 çº¿æ®µä¸å¤šé‡ç›´çº¿
è¿™ä¸€èŠ‚ç¨‹åºå†™å¾—å¾ˆå¥½ï¼Œæ²¡æœ‰ä»€ä¹ˆæ€§è´¨æ–¹é¢çš„é”™è¯¯ã€‚ä½†æ˜¯æœ‰ä½œè€…ä¸€å†æŒ‡å‡ºçš„åŸºæœ¬é”™è¯¯ï¼šPythonå¤§å°å†™æ•æ„Ÿé”™è¯¯ã€‚

å‰é¢ä¸¤ä¸ªå‡½æ•°é‡‡ç”¨äº†é©¼å³°å‘½åæ³•ï¼Œåé¢åˆå…¨éƒ¨ç”¨å°å†™å•è¯å‘½åï¼Œç²—å¿ƒã€‚è¦æƒ³ç¨‹åºè¿è¡Œï¼ŒæŠŠå‰é¢ä¸¤ä¸ªå‡½æ•°åå…¨æ”¹æˆå°å†™ã€‚è¿™é‡Œå°±ä¸è´´å‡ºæ¥äº†ã€‚

ä»å‡½æ•°ä¸å˜é‡å‘½åçš„æ–¹å¼ï¼Œå¯ä»¥æ˜æ˜¾çš„æ„Ÿè§‰åˆ°ï¼Œè¿™æœ¬ä¹¦çš„ä½œè€…æ˜¯å‡ ä¸ªäººï¼Œå‰é¢æŒºæ­£å¼çš„ä»‹ç»å˜é‡å‘½åæ–¹å¼ï¼Œåé¢å…¨éƒ¨å¼ƒç”¨ï¼Œå¼€å§‹æ”¾é£è‡ªæˆ‘å¼å‘½åï¼›å‡½æ•°çš„å‘½åï¼Œæœ‰é©¼å³°æ³•ï¼Œæœ‰å…¨å°å†™çš„ï¼Œåº”è¯¥å‡ºè‡ªå‡ ä¸ªä¸åŒçš„é«˜æ‰‹ã€‚

#### 8.7.1 æ§åˆ¶ç‚¹æ›²çº¿
ç»™æ›²çº¿å€’è§’çš„ç¨‹åºï¼Œè¿è¡Œä¸äº†ã€‚å› ä¸ºè®¡ç®—ä¸¤ç‚¹ä¹‹é—´ä¸­é—´ç‚¹ä½¿ç”¨çš„åŒ¿åå‡½æ•° *between* ï¼ŒæŠŠVector3då¯¹è±¡å’ŒPoint3då¯¹è±¡ç›´æ¥ç›¸åŠ ï¼Œç¨‹åºä¸è®¤ã€‚
w1ã€w2ç”Ÿæˆçš„æ˜¯Vector3Då¯¹è±¡ä¹Ÿä¸æ˜¯Point3dç‚¹å¯¹è±¡ã€‚æŠŠæ‰€æœ‰çš„å¯¹è±¡ç»Ÿä¸€è½¬æ¢ä¸ºPoint3då¯¹è±¡ï¼Œå°±èƒ½ä½¿ç¨‹åºæ­£å¸¸è¿è¡Œã€‚å¦‚ä¸‹ï¼š


```python
import rhinoscriptsyntax as rs


def blendcorners():
    polyline_id = rs.GetObject("Polyline to blend", 4, True, True)
    if not polyline_id:
        return
    vertices = rs.PolylineVertices(polyline_id)
    if not vertices:
        return
    radius = rs.GetReal("Blend radius", 1.0, 0.0)
    if radius is None:
        return
    
    between = lambda a, b: rs.CreatePoint((a + b) / 2.0)
    newverts = []
    for i in range(len(vertices) - 1):
        a = vertices[i]
        b = vertices[i + 1]
        segment_length = rs.Distance(a, b)
        vec_segment = rs.PointSubtract(b, a)
        vec_segment = rs.VectorUnitize(vec_segment)

        if radius < (0.5 * segment_length):
            vec_segment = rs.VectorScale(vec_segment, radius)
        else:
            vec_segment = rs.VectorScale(vec_segment, 0.5 * segment_length)

        w1 = rs.CreatePoint(rs.VectorAdd(a, vec_segment))
        w2 = rs.CreatePoint(rs.VectorSubtract(b, vec_segment))
        newverts.append(a)
        newverts.append(between(a, w1))
        newverts.append(w1)
        newverts.append(between(w1, w2))
        newverts.append(w2)
        newverts.append(between(w2, b))
    newverts.append(vertices[len(vertices) - 1])
    rs.AddCurve(newverts, 5)
    rs.DeleteObject(polyline_id)


blendcorners()
```

#### 8.7.3 å‡ ä½•æ›²çº¿ç‰¹æ€§

ä¹¦é‡Œè¿™ä¸ªç¨‹åºï¼Œå­˜åœ¨ä¸¤ä¸ªé—®é¢˜ï¼š

1. ç”¨äºä¿å­˜ç”¨æˆ·ç”Ÿæˆç‰©ä½“çš„åˆ—è¡¨ *preview* æ˜¯ä¸€ä¸ªåµŒå¥—åˆ—è¡¨ï¼Œå¦‚æœä¸æ›´æ”¹åˆ é™¤æ–¹å¼ï¼Œé™¤äº†é»˜è®¤å‚æ•°å¯ä»¥è¿è¡Œï¼Œç”¨æˆ·è¾“å…¥ä»»ä½•è‡ªå®šå‚æ•°æ—¶ï¼Œä¼šèµ°åˆ°åˆ é™¤ *preview* å†…åˆ—è¡¨è¿™ä¸€æ­¥æŠ¥é”™ï¼Œå› ä¸º *rs.DeleteObjects()* åˆ†æ *preview* åˆ—è¡¨å†…çš„å…ƒç´ å¹¶ä¸æ˜¯æœ‰æ•ˆçš„Rhinoç‰©ä½“ã€‚
2. åœ¨æ¥æ”¶ç”¨æˆ·å‚æ•°è¿™ä¸€æ­¥ï¼Œå¹¶ä¸èƒ½å¤„ç†ç”¨æˆ·éšæ„è¾“å…¥çš„æ— æ•ˆä¿¡æ¯ã€‚

æ›´æ”¹åçš„ç¨‹åºå¦‚ä¸‹ï¼š

```Python
def createcurvaturegraph():
    curve_ids = rs.GetObjects("Curves for curvature graph", 4, False, True, True)
    if not curve_ids:
        return

    samples = 10
    scale = 100.0

    preview = []
    while True:
        rs.EnableRedraw(False)
        for p in preview:
            for item_list in p:
                rs.DeleteObjects(item_list)
        preview = []
        for id in curve_ids:
            cg = addcurvaturegraph(id, samples, scale)
            preview.append(cg)
        rs.EnableRedraw(True)

        result = rs.GetString(
            "Curvature settings", "Accept", ("Samples", "Scale", "Accept")
        )
        if not result:
            for p in preview:
                for item_list in p:
                    rs.DeleteObjects(item_list)
            break
        result = result.upper()
        if result == "ACCEPT":
            break
        elif result == "SAMPLES":
            numsamples = rs.GetInteger(
                "Number of samples per knot-span", samples, 3, 100
            )
            if numsamples:
                samples = numsamples
        elif result == "SCALE":
            sc = rs.GetReal("Scale of the graph", scale, 0.01, 1000.0)
            if sc:
                scale = sc
        else:
            rs.Prompt('Please input/select a correct parameter:')
            rs.Sleep(750)
            continue
```

